---

- name: Add nip.io to interactive tool entry url
  lineinfile:
    path: "{{ interactivetool_manager_file }}"
    regexp: ^(\s*rval = f'{protocol}//{self.get_entry_point_subdomain\(trans, entry_point\)}.{request_host})(/')$
    backrefs: yes
    line: \1.nip.io\2
    state: present
  notify: Restart galaxy

- name: Fix rstudio container version
  lineinfile:
    path: "{{ rstudio_interactive_file }}"
    regexp: ^(\s*<container type="docker">quay.io/erasche/docker-rstudio-notebook:).*(</container>)
    backrefs: yes
    line: \1ie2\2
    state: present

- name: Remove syslog from rstudio container startup script
  lineinfile:
    path: "{{ rstudio_interactive_file }}"
    regexp: ^\s*/etc/init.d/syslog-ng start &&$
    state: absent

- name: Set www-root-path in rstudio container startup script
  replace:
    path: "{{ rstudio_interactive_file }}"
    regexp: (sleep 5 &&\n)\n(\s*)(chmod 777 /tmp -R &&)
    replace: |
      \1
      \2sed -i '2awww-root-path=/rstudio' /etc/rstudio/rserver.conf &&
      \2pkill -9 rserver &&
      \2\3

- name: Fix jupyter notebook interactive tool command
  replace:
    path: "{{ jupyter_interactive_file }}"
    regexp: ^(\s*)(cd \./jupyter/ &&)\n(\s*export PATH=/home/jovyan/\.local/bin:.\$PATH &&)
    replace: |
      \1\2
      \1export HOME=/home/jovyan/ &&
      \3

- name: Fix containers not removed when interactive tool is stopped
  replace:
    path: "{{ pulsar_kill_util_file }}"
    regexp: (def kill_pid\(pid, use_psutil=True\):\n)\s*if use_psutil and Process:\n\s*_psutil_kill_pid\(pid\)\n\s*else:\n\s*_stock_kill_pid\(pid\)
    replace: \1    subprocess.Popen(args=f"pkill -9 -P {pid}", shell=True)
  notify: Restart galaxy