---

- name: Add nip.io to interactive tool entry url
  lineinfile:
    path: "{{ interactivetool_manager_file }}"
    regexp: ^(\s*rval = '\%s//%s-%s.%s.%s.%s)(.*)$
    backrefs: yes
    line: \1.nip.io\2
    state: present

- name: Fix docker_util.py parse_port_text function
  lineinfile:
    path: "{{ docker_util_file }}"
    regexp: ^\s{12}hostname, port = host.split\(':'\)
    backrefs: yes
    line: |2
                  hostname, port = host.rsplit(':', 1)
                  if hostname == '::':
                      continue
    state: present

- name: Add config_files to pulsar queue_job function
  replace:
    path: "{{ pulsar_runner_file }}"
    regexp: ^\s{16}(job_directory_files\.append\(tool_script\))\n\s{12}(client_job_description = ClientJobDescription\()
    replace: |2
                      \1
                      config_files.append(tool_script)
                  # Following is job destination environment variables
                  env = client.env
                  # extend it with tool defined environment variables
                  tool_envs = job_wrapper.environment_variables
                  env.extend(tool_envs)
                  for tool_env in tool_envs:
                      job_directory_path = tool_env.get("job_directory_path")
                      if job_directory_path:
                          config_files.append(job_directory_path)
                  \2
