---

- name: Proxying the proxy
  include_tasks: double_proxy.yml

- name: Enable Interactive Tools
  include_tasks: interactive_tools.yml

- name: Fix Interactive Tools for Galaxy release_20.05
  include_tasks: interactive_tools_fixes.yml