---

- name: Reload nginx
  service:
    name: nginx
    state: reloaded
    
- name: Restart galaxy
  service:
    name: galaxy
    state: restarted

- name: Restart docker
  service:
    name: docker
    state: restarted